// File generated by FlutterFire CLI.
// TODO: Replace with your actual Firebase configuration

// This is a placeholder. To configure Firebase:
// 1. Create a Firebase project at https://console.firebase.google.com
// 2. Add Android and iOS apps
// 3. Run: flutter pub global activate flutterfire_cli
// 4. Run: flutterfire configure

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError('Platform not supported');
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEUvyqfx1ptX572lxmg9lvYfGm4h3IALM',
    appId: '1:139151788468:android:81292998b87d30856a0ae1',
    messagingSenderId: '139151788468',
    projectId: 'runlift-prod',
    storageBucket: 'runlift-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5kKZ1h-Oac-K6N_L5F9hielqRlEZyyMs',
    appId: '1:139151788468:ios:b8fd388e76645f916a0ae1',
    messagingSenderId: '139151788468',
    projectId: 'runlift-prod',
    storageBucket: 'runlift-prod.firebasestorage.app',
    iosClientId: '139151788468-cqcov75ut0kmatt3hpq50c13l19nghpr.apps.googleusercontent.com',
    iosBundleId: 'com.runlift.runlift',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxNf4ZC4nxJrKd31lXI9gxCD8Rhurn8rs',
    appId: '1:139151788468:web:453b567d972ec9d76a0ae1',
    messagingSenderId: '139151788468',
    projectId: 'runlift-prod',
    authDomain: 'runlift-prod.firebaseapp.com',
    storageBucket: 'runlift-prod.firebasestorage.app',
    measurementId: 'G-LCEQKBBKVL',
  );

}